#!/bin/bash

# This loop will fill a buffer with our infos, and output it to stdout.
i_pkgs='\ue14d'   # pacman
i_mail='\ue072'   # mail icon
i_wifi='\ue0f0'   # signal
i_time='\ue016'   # clock
i_load='\ue0c5'   # micro chip
i_musk='\ue04d '  # headphones
i_alsa='\ue05d'   # speaker
i_tmp='\ue0cf'    # thermometer 
i_term='\ue01e'   # term
i_monitor='\ue09f' # monitor 
i_ecrcl='\ue0f6'
i_fcrcl='\ue098'
i_cal='\ue01e'
i_bt='\ue004'

SOUNDIC=`echo -e $i_alsa`
MEMIC=`echo -e $i_load `
MUSIC=`echo -e $i_musk`
TEMPIC=`echo -e $i_tmp`
PACIC=`echo -e $i_pkgs`
CLKIC=`echo -e $i_time`
TERMIC=`echo -e $i_term`
FCRCL=`echo -e $i_fcrcl`
ECRCL=`echo -e $i_ecrcl`
MAILIC=`echo -e $i_mail`
CALIC=`echo -e $i_cal`
WIFIIC=`echo -e $i_wifi`
SKULL=`echo -e '\u2620'`

while :; do
    clk=`date "+%a %b. %e, %Y - %I:%M %p"`
    now_playing=`mpc current`
    buf=" "
    buf="${buf}%{A:google-chrome "www.gmail.com" &:} ${MAILIC} Mail%{A} | "
    buf="${buf}%{A:google-chrome "www.google.com/calendar" &:}${CALIC} Calendar%{A} | "
    buf="${buf}%{A:google-chrome "news.google.com" &:} ${TERMIC} News%{A} | "
    buf="${buf}%{A:gnome-control-center.real sound &:}${SOUNDIC} Sound%{A} | "
    buf="${buf}%{A:gnome-control-center.real bluetooth &:}${WIFIIC} BT%{A} | "
    buf="${buf}%{c}%{A:gmpc &:}${MUSIC} ${now_playing}%{A}%{c}"
    buf="${buf}%{r}${CLKIC} ${clk}%{r}"

    echo $buf
    # use `nowplaying scroll` to get a scrolling output!
    sleep 1 # The HUD will be updated every second
done
