#!/bin/sh

bspc config border_width        2
bspc config window_gap          5

bspc monitor -d 1 2 3 4

bspc config top_padding           14

bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_by_distance     true
bspc config focus_follows_pointer true

bspc config active_border_color "#3F4B9C"
bspc config focused_border_color "#3F4B9C"
bspc config presel_border_color "#181818"
bspc config urgent_border_color "#C90515"
bspc config focused_locked_border_color "#8c644c"


bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer true
bspc config auto_alternate true
bspc config auto_cancel true
bspc config normal_border_color "#332d29"
bspc config active_border_color "#817267"
bspc config focused_border_color "#504339"
bspc config presel_border_color "#9a875f"
bspc config urgent_border_color "#9f7155"
bspc config focused_locked_border_color "#9a875f"
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1

bspc config normal_frame_opacity  0.0
bspc config focused_frame_opacity 0.1

bspc rule -a Chrome desktop=^2
bspc rule -a Thunar floating=on
bspc rule -a Spotify floating=on

feh --bg-scale backgrounds/bg.jpg &

/home/demarr/.config/bspwm/panel &
