#!/bin/bash

cd $(dirname $0)
source /home/demarr/.config/bspwm/panel/config

if [ $(pgrep -cx panel) -gt 1 ] ; then
    printf "%s\n" "The panel is already running." >&2
    exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding $PANEL_HEIGHT
bspc control --subscribe > "$PANEL_FIFO" &

. panel_colors

#conky -c ./panel_conky > "$PANEL_FIFO" &
clock -sf 'S%I:%M %p' > "$PANEL_FIFO" &
xtitle -sf 'T%s' > "$PANEL_FIFO" &

PANEL_FONT_FAMILY='-*-terminus-medium-r-normal-*-12-*-*-*-c-*-*-1'
PANEL_FONT_2='-misc-stlarch-medium-r-normal--10-100-75-75-c-80-iso10646-1'
#PANEL_FONT_2='-*-stlarch-medium-r-*-*-10-*-*-*-*-*-*-*'

#cat "$PANEL_FIFO" | ./panel_bar | bar -f "$PANEL_FONT_FAMILY","$PANEL_FONT_2" -F "$COLOR_FOREGROUND" -B "$COLOR_BACKGROUND" -g "$PANEL_GEOMETRY" -u $LINEHEIGHT &
cat "$PANEL_FIFO" | ./panel_bar | bar -g x$PANEL_HEIGHT -f "$PANEL_FONT_2","$PANEL_FONT_FAMILY" -F "$COLOR_FOREGROUND" -B "$COLOR_BACKGROUND" &

wait

