#!/bin/bash

source /home/demarr/.config/bspwm/panel/config

./panel_colors

num_mon=$(bspc query -M | wc -l)

while read -r line ; do
    case $line in
        S*)
            wthr=`echo -e "$(weather kwst | awk '/Temperature/ {print $2}')"`
            cndt=`echo -e "$(weather kwst | awk '/Sky/ {print $3}')"`
            tmp=`echo -e "$(sensors coretemp-isa-0000 | awk '/Physical/ { print $4 }')"`
            mem=`echo -e "$(free -m | grep --line-buffered Mem | awk '{print $3}')Mb"`
            vol=`amixer sget Master | sed -n "0,/.*\[\([0-9]\+\)%\].*/s//\1/p"`
            package=`pacman -Qq | wc -l`
            clk=`date "+%I:%M %p"`
            #sys_infos="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG} %{F$YELLOW}${PACIC}%{F$FOREG} ${package} %{F$THECOLOR}${SOUNDIC} %{F$FOREG}${vol}%% %{F$THECOLOR}${TEMPIC} %{F$FOREG}${wthr} ${cndt}%{F$FOREG} %{F$THECOLOR}${CLKIC} %{F$FOREG}${clk}"
            sys_infos="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG} %{F$THECOLOR}${SOUNDIC} %{F$FOREG}${vol}%% %{F$THECOLOR}${TEMPIC} %{F$FOREG}${wthr} ${cndt}%{F$FOREG} %{F$THECOLOR}${CLKIC} %{F$FOREG}${clk}"
            ;;
        T*)
            #xtitle output
			title="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG}%{F$FOREG}${line#?}%{F$FOREG}"
            ;;
        W*)
            wm_infos=""
            IFS=':'
            set -- ${line#?}
            while [ $# -gt 0 ] ; do
                item=$1
                name=${item#?}
                case $item in
                    M*)
                        # active monitor
						if [ $num_mon -gt 1 ] ; then
							wm_infos="$wm_infos %{F$COLOR_ACTIVE_MONITOR_FG}%{B$COLOR_ACTIVE_MONITOR_BG}${name}%{B-}%{F-}  "
						fi
						;;
					m*)
						# inactive monitor
						if [ $num_mon -gt 1 ] ; then
							wm_infos="$wm_infos %{F$COLOR_INACTIVE_MONITOR_FG}%{B$COLOR_INACTIVE_MONITOR_BG} ${name}%{B-}%{F-}"
						fi
						;;
					O*)
						# focused occupied desktop
						wm_infos="${wm_infos}%{F$COLOR_FOCUSED_OCCUPIED_FG}%{B$COLOR_FOCUSED_OCCUPIED_BG}%{U$COLOR_FOREGROUND}%{+u} ${FCRCL}%{-u}%{B-}%{F-}"
						;;
					F*)
						# focused free desktop
						wm_infos="${wm_infos}%{F$COLOR_FOCUSED_FREE_FG}%{B$COLOR_FOCUSED_FREE_BG}%{U$COLOR_FOREGROUND}%{+u} ${ECRCL}%{-u}%{B-}%{F-}"
						;;
					U*)
						# focused urgent desktop
						wm_infos="${wm_infos}%{F$COLOR_FOCUSED_URGENT_FG}%{B$COLOR_FOCUSED_URGENT_BG}%{U$COLOR_FOREGROUND}%{+u} ${FCRCL}%{-u}%{B-}%{F-}"
						;;
					o*)
						# occupied desktop
						wm_infos="${wm_infos}%{F$COLOR_OCCUPIED_FG}%{B$COLOR_OCCUPIED_BG} ${FCRCL}%{B-}%{F-}"
						;;
					f*)
						# free desktop
						wm_infos="${wm_infos}%{F$COLOR_FREE_FG}%{B$COLOR_FREE_BG} ${ECRCL}%{B-}%{F-}"
						;;
					u*)
						# urgent desktop
						wm_infos="${wm_infos}%{F$COLOR_URGENT_FG}%{B$COLOR_URGENT_BG} ${FCRCL} %{B-}%{F-}"
						;;
					L*)
						# layout
						#wm_infos="$wm_infos  %{F$COLOR_LAYOUT_FG}%{B$COLOR_LAYOUT_BG} ${name} %{B-}%{F-}"
						;;
                esac
                shift
            done
            ;;
    esac
    #printf "%s\n" "%{l}$wm_infos%{c}$title%{r}$sys_infos"
	#printf "%s\n" "%{l}${wm_infos}%{c}${title}%{r}${sys_infos}"
    #printf "%s\n" "%{l}${wm_infos}  %{F$THECOLOR}${art}%{F$FOREG} ${tit} %{c} $title %{r} $sys_infos "
    printf "%s\n" "%{l}$title%{c}${wm_infos} %{r}$sys_infos "
done
