#!/bin/sh

PANEL_FONT_FAMILY='-*-terminus-medium-r-normal-*-12-*-*-*-c-*-*-1'
PANEL_FONT_2='-misc-stlarch-medium-r-normal--10-100-75-75-c-80-iso10646-1'

PANEL_FIFO=/tmp/panel-fifo
[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

/home/demarr/.config/bspwm/barmk | bar -f $PANEL_FONT_2,$PANEL_FONT_FAMILY | while read line; do eval "$line"; done

